exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: true
    permalink: /:path/

# Site title and description 
title: "analytics.phila.gov | The City of Philadelphia's government's web traffic."
description: "Official data on web traffic to City of Philadelphia government websites. Published by the Office of Innovation and Technology."

# Site's own URL
url: http://analytics.phila.gov 

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Participating Websites

# Default data url
data_url: http://analytics.phila.gov/testdata

# GitHub information
org_name: CityofPhiladelphia
repo_name: analytics.phila.gov

# twitter information
twitter: PhilaGovData

sass:
  sass_dir: sass
  style: nested
